import type { SidebarsConfig } from '@docusaurus/plugin-content-docs';

// The sidebar is auto-generated from the `docs/` directory structure.
// Order of categories and pages is controlled by:
//   - `sidebar_position` in the page frontmatter;
//   - `_category_.json` in the folder (label, position, collapsed, collapsible).
const sidebars: SidebarsConfig = {
  mainSidebar: [
    {
      type: 'autogenerated',
      dirName: '.',
    },
  ],
};

export default sidebars;
